CREATE TYPE "ConsultationType" AS ENUM (
  'FIRST_CONSULTATION',
  'CONSULTATION',
  'CONTROL',
  'FOLLOW_UP',
  'EMERGENCY',
  'VACCINATION',
  'ANNUAL_VISIT',
  'PRESCRIPTION_RENEWAL',
  'TELECONSULTATION',
  'EXAM_RESULT',
  'MEDICAL_CERTIFICATE',
  'OTHER'
);

ALTER TABLE "Consultation"
  ADD COLUMN "type" "ConsultationType" NOT NULL DEFAULT 'CONSULTATION',
  ADD COLUMN "motif" TEXT;
